import Head from 'next/head'
import Image from 'next/image'
import { useRef, useState } from 'react'
import { HeaderFixed } from '../components/HeaderFixed'
import { HeaderSticky } from '../components/HeaderSticky'
import { TextInput } from '../components/TextInput'
import useAutosizeTextArea from '../functions/useAutosizeTextArea'
import styles from '../styles/Home.module.css'

export default function Home() {
  const [value, setValue] = useState("");
  const textAreaRef = useRef<HTMLTextAreaElement>(null);

  useAutosizeTextArea(textAreaRef.current, value);
  const handleChange = (evt: React.ChangeEvent<HTMLTextAreaElement>) => {
    const val = evt.target?.value;
    setValue(val);
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HeaderFixed />
      <HeaderSticky />
      <TextInput textAreaRef={textAreaRef} handleChange={handleChange}/>
    </>
  )
}
