import Head from 'next/head'
import Image from 'next/image'
import { HeaderFixed } from '../components/HeaderFixed'
import { HeaderSticky } from '../components/HeaderSticky'
import { TextInput } from '../components/TextInput'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HeaderSticky />
      <main className={styles.main}>
       <TextInput />
      </main>
      <footer className={styles.footer}>
        This is a test page
      </footer>
    </>
  )
}
